/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul9_praktikum2;

/**
 *
 * @author asus
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconabul = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtxthari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtbulan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFMincho-UB", 1, 36)); // NOI18N
        jLabel1.setText("Pencari Bulan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 320, 60);

        jLabel2.setText("Bulan Ke - ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 110, 14);

        jconabul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilihan--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jconabul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconabulActionPerformed(evt);
            }
        });
        getContentPane().add(jconabul);
        jconabul.setBounds(110, 70, 200, 30);

        jLabel3.setText("Jumlah Hari");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 80, 14);
        getContentPane().add(jtxthari);
        jtxthari.setBounds(120, 200, 250, 30);

        jLabel4.setText("Bulan ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 80, 14);
        getContentPane().add(jtxtbulan);
        jtxtbulan.setBounds(120, 150, 250, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 380, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jconabulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconabulActionPerformed
    if(jconabul.getSelectedItem().equals("1")){
            jtxtbulan.setText("JANUARI");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("2")){
            jtxtbulan.setText("FEBRUARI");
            jtxthari.setText("28 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("3")){
            jtxtbulan.setText("MARET");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("4")){
            jtxtbulan.setText("APRIL");
            jtxthari.setText("30 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("5")){
            jtxtbulan.setText("MEI");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("6")){
            jtxtbulan.setText("JUNI");
            jtxthari.setText("30 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("7")){
            jtxtbulan.setText("JULI");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("8")){
            jtxtbulan.setText("AGUSTUS");
            jtxthari.setText("30 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("9")){
            jtxtbulan.setText("SEPTEMBER");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("10")){
            jtxtbulan.setText("OKTOBER");
            jtxthari.setText("30 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("11")){
            jtxtbulan.setText("NOVEMBER");
            jtxthari.setText("31 Hari");
        }
    else
        if(jconabul.getSelectedItem().equals("12")){
            jtxtbulan.setText("DESEMBER");
            jtxthari.setText("30 Hari");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jconabulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconabul;
    private javax.swing.JTextField jtxtbulan;
    private javax.swing.JTextField jtxthari;
    // End of variables declaration//GEN-END:variables
}
